export { default as Hero1 } from './Hero1'
export { default as Hero8 } from './Hero8'
export { default as Hero7 } from './Hero7'
export { default as Hero12 } from './Hero12'
export { default as Hero34 } from './Hero34'
export { default as Hero24 } from './Hero24'

export { hero1Config } from './Hero1/config'
export { hero8Config } from './Hero8/config'
export { hero7Config } from './Hero7/config'
export { hero12Config } from './Hero12/config'
export { hero34Config } from './Hero34/config'
export { hero24Config } from './Hero24/config'
