export { default as Hero8 } from './Hero8'
export { default as Hero1 } from './Hero1'
export { default as Hero7 } from './Hero7'
export { default as Hero12 } from './Hero12'
export { default as Hero24 } from './Hero24'
export { default as Hero34 } from './Hero34'
