name: 🚀 Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'FR']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is
      placeholder: Tell us about the feature...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problems does it solve?
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide specific examples of how this feature would be used
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to work on this feature?
      options:
        - 'Yes'
        - 'No'
        - 'Maybe (I need guidance)'
